# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-22 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('street_address', models.CharField(max_length=250)),
                ('headshot', models.ImageField(blank=True, upload_to=b'')),
            ],
        ),
    ]
