# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='headshot',
            field=models.CharField(max_length=1000),
        ),
    ]
