# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0002_auto_20190227_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='headshot',
            field=models.FileField(upload_to=b''),
        ),
    ]
